spring:
  datasource:
    url: jdbc:h2:~/Documents/practices/jpashop/db;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # hibernate 가 생성한 SQL을 LOGGER로 찍음.